# Generated by Django 3.0.6 on 2020-05-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20200510_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='total',
            new_name='price',
        ),
    ]
